version: '3.1'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: contactTracing
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
